apiVersion: apps/v1
kind: Deployment
metadata:
  name: emp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emp
  template:
    metadata:
      labels:
        app: emp
    spec:
      containers:
      - name: emp
        image: reenaso16/emp_mn:latest
        ports:
        - containerPort: 9090
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://mysql-service:3306/demo?useSSL=false&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          value: root
        - name: SPRING_DATASOURCE_PASSWORD
          value: root

